DROP DATABASE IF EXISTS tpcds_hive CASCADE;
CREATE DATABASE tpcds_hive;
USE tpcds_hive;

CREATE TABLE call_center AS SELECT * FROM tpcds.call_center;
CREATE TABLE catalog_page AS SELECT * FROM tpcds.catalog_page;
CREATE TABLE catalog_returns AS SELECT * FROM tpcds.catalog_returns;
CREATE TABLE catalog_sales AS SELECT * FROM tpcds.catalog_sales;
CREATE TABLE customer AS SELECT * FROM tpcds.customer;
CREATE TABLE customer_address AS SELECT * FROM tpcds.customer_address;
CREATE TABLE customer_demographics AS SELECT * FROM tpcds.customer_demographics;
CREATE TABLE date_dim AS SELECT * FROM tpcds.date_dim;
CREATE TABLE dbgen_version AS SELECT * FROM tpcds.dbgen_version;
CREATE TABLE household_demographics AS SELECT * FROM tpcds.household_demographics;
CREATE TABLE income_band AS SELECT * FROM tpcds.income_band;
CREATE TABLE inventory AS SELECT * FROM tpcds.inventory;
CREATE TABLE item AS SELECT * FROM tpcds.item;
CREATE TABLE promotion AS SELECT * FROM tpcds.promotion;
CREATE TABLE reason AS SELECT * FROM tpcds.reason;
CREATE TABLE ship_mode AS SELECT * FROM tpcds.ship_mode;
CREATE TABLE store AS SELECT * FROM tpcds.store;
CREATE TABLE store_returns AS SELECT * FROM tpcds.store_returns;
CREATE TABLE store_sales AS SELECT * FROM tpcds.store_sales;
CREATE TABLE time_dim AS SELECT * FROM tpcds.time_dim;
CREATE TABLE warehouse AS SELECT * FROM tpcds.warehouse;
CREATE TABLE web_page AS SELECT * FROM tpcds.web_page;
CREATE TABLE web_returns AS SELECT * FROM tpcds.web_returns;
CREATE TABLE web_sales AS SELECT * FROM tpcds.web_sales;
CREATE TABLE web_site AS SELECT * FROM tpcds.web_site;
